name: run tests on mac

on:
  push:
  pull_request:

jobs:
  github_mactest:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-python@v2
      with:
          python-version: '3.7'
    - run: |
       brew install boost boost-mpi fftw
       brew install hdf5-mpi
       pip3 install numpy cython h5py scipy
    - run: |
        export myconfig=maxset with_cuda=false test_timeout=600
        bash maintainer/CI/build_cmake.sh
